### ISSUE TITLE
Some questions about neuri

### ISSUE THREAD

**Issue by AnonymousChaseDreamer** [ise-uiuc/neuri-artifact#3]
Hi, jiawei, jinjun and Yuyao.

It's really an interesting and solid work. Thank you for your shared scripts and docker! I really appreciate your open-source spirit!

I still have some questions as follows (about neuri and experiment replication).
1.  `About neuri`: At present, neuri mainly conducts DL-framework testing through inductive program synthesis. Can neuri test `IR` (ONNX) and `Compiler` (TVM) like nnsmith ? Because you said neuri would be merged into nnsmith. If possible, I want to use neuri to test IR and DL Compiler.
2. `About experiment replication`:  I follow your instructions to download the docker image. When go to [S2: Collect coverage](https://github.com/ise-uiuc/neuri-artifact#s2-collect-coverage), there not exits `torch` package in the conda virtual environment `cov`. Because when I execute `python experiments/evaluate_models.py  --root $(pwd)/gen/torch-neuri-n5.models          --model_type torch --backend_type torchjit --parallel $(nproc)`. I meet many errors: `ModuleNotFoundError: No module named 'torch'`. Can you check it  again in your docker?

Lastly, here is a minor suggestion. In README, [Figure 6 (a)](https://github.com/ise-uiuc/neuri-artifact#figure-6-a) and [Figure 6 (b)](https://github.com/ise-uiuc/neuri-artifact#figure-6-b) seems to be reversed from those in the paper.

Forgive me if I'm just a newcomer to DL testing :) 
Looking forward to your reply. Thx in advance :)

**Comment by AnonymousChaseDreamer** [comment]
Sorry, `About experiment replication`: I check it again, I need to use `git pull origin main` not `git clone`
Here is the related in coda list:
```
torch                     1.14.0a0+gitf7520cb           dev_0    <develop>
```

**Comment by AnonymousChaseDreamer** [comment]
To be honest, I still don't understand whether neuri can be applied to tvm and ort.

Thank you so much if any clarification.

cc @ganler

**Comment by ganler** [comment]
@AnonymousChaseDreamer  I'm sorry I just see this issue until you ping'ed me as I was not ["watching"](https://docs.github.com/en/rest/activity/watching?apiVersion=2022-11-28) all activities of the repo. Let me check your questions now.

**Comment by ganler** [comment]
> About neuri: At present, neuri mainly conducts DL-framework testing through inductive program synthesis. Can neuri test IR (ONNX) and Compiler (TVM) like nnsmith ? Because you said neuri would be merged into nnsmith. If possible, I want to use neuri to test IR and DL Compiler.

Sure thing. So the NeuRI artifact is basically build on NNSmith. In other words, NeuRI improves NNSmith by extending the available set of operator rules and most of NeuRI has been integrated into NNSmith (but I'm sorry right now we still cannot use the NNSmith code to fully function as NeuRI -- more engineering needs to be done by me as I don't want to use these pickle binary to store the rules which is not a good practice for a source-code repository).

Because NNSmith supports TVM, consequently NeuRI supports TVM as well.

The way NeuRI/NNSmith tests TVM/ORT/TensorRT is that:

1. NeuRI/NNSmith produces PyTorch models
2. PyTorch models can be converted to ONNX models
3. ONNX models are imported by TVM/ORT/TensorRT
4. Differential testing

More concretely, look at here:

https://github.com/ise-uiuc/neuri-artifact/blob/7be03abad2fa9c513b3cc91c92959f4df08e38f5/fuzz.sh#L49

`model.type` can be set to `onnx` and `` can be set to `tvm`, `tensorrt`, `onnxruntime` etc. (see https://github.com/ise-uiuc/neuri-artifact/blob/main/neuri/backends/factory.py).

Honestly I never tested this path but I am quite confident that it should not be too hard to make it work. The only problem I can forsee is that the some of the produced PyTorch models might not be successfully converted into ONNX for various reasons but could fine to just skip it.

**Comment by ganler** [comment]
> Lastly, here is a minor suggestion. In README, [Figure 6 (a)](https://github.com/ise-uiuc/neuri-artifact#figure-6-a) and [Figure 6 (b)](https://github.com/ise-uiuc/neuri-artifact#figure-6-b) seems to be reversed from those in the paper.

:D Ah that is my bad! Thank you for spotting the typo for us!!

**Comment by ganler** [comment]
@AnonymousChaseDreamer I think I have replied all unsolved questions so far. Meanwhile I strongly suggest you to play with [nnsmith](https://github.com/ise-uiuc/nnsmith) first and we have some [documents](https://github.com/ise-uiuc/nnsmith/tree/main/doc) for that. When you are familiar enough with NNSmith I am pretty sure NeuRI would just be easy to use as well. :D

Let me know any further questions or suggestions! Thanks for you interest!

**Comment by AnonymousChaseDreamer** [comment]
Thx for your help :D
